version: '3.8'

services:
  web:
    build:
      context: ./Rule_Engine_web_app
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    expose:
      - 5000


  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web
